version: "3"
services:
    listings-services:
        build: "./listings-service"
        depends_on:
            - listings-service-db
        environment:
            - DB_URI=mysql://aziz:root@listings-service-db/db?charset=UTF8
        volumes:
            - ./listings-service:/opt/app

    listings-service-db:
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
        image: mysql:5.7.20
        ports:
            - 0.0.0.0:7200:3306

    users-services:
        build: "./users-service"
        depends_on:
            - users-service-db
        environment:
            - DB_URI=mysql://aziz:root@users-service-db/db?charset=UTF8
        volumes:
            - ./users-service:/opt/app

    users-service-db:
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
        image: mysql:5.7.20
        ports:
            - 0.0.0.0:7201:3306