version: "3"
services:
    listings-services:
        build: "./listings-service"
        depends_on:
            - listings-service-db
        volumes:
            - ./listings-service:/opt/app

    listings-service-db:
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
        image: mysql:5.7.20

    users-services:
        build: "./users-service"
        depends_on:
            - users-service-db
        volumes:
            - ./users-service:/opt/app

    users-service-db:
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
        image: mysql:5.7.20
